Mssql docs
kysely-org/kysely pull request #724
Opened 2023-10-06 02:14 UTC by gittgott

closes #713

I couldn't get deno or bun to work with the dialect. Deno was having issues connecting to the database with the message `Error: Failed to connect to localhost:1433 - tlssock._start is not a function`. Bun was having issues with tarn with the message `Failed to connect to localhost:1433 - socket must be an instance of net.Socket`.

Since this wasn't working for me, I stated that bun and deno didn't support the mssql dialect in the docs. Just want to make sure that they aren't currently known to work.

Thanks!

2023-10-06 10:13 UTC, igalklebanov reviewed
Hey 👋 

Thanks! 💪 

Let some initial comments..

2023-10-06 10:13 UTC, igalklebanov commented on site/docs/getting-started/Dialects.tsx
> +        choose from. Find out more at{' '}
- Let's use the official long name and abbreviation.
- Let's place it before SQLite as it is still more popular.

```suggestion
        There are 4 built-in dialects for PostgreSQL, MySQL, Microsoft SQL Server 
        (MSSQL), and SQLite. Additionally, the community has implemented several
        dialects to choose from. Find out more at{' '}
```

2023-10-06 10:13 UTC, igalklebanov commented on site/docs/getting-started/Summary.tsx
> +      .addColumn('id', 'integer', (cb) => cb.primaryKey().modifyEnd(sql\`IDENTITY(1,1)\`))
let's leave a TODO here to update this once we add `identity(1,1)` to core.

2023-10-06 10:13 UTC, igalklebanov commented on site/docs/getting-started/shared.tsx
> +  mssql: 'MSSQL',
```suggestion
  mssql: 'Microsoft SQL Server (MSSQL)',
```

2023-10-06 10:13 UTC, igalklebanov commented on site/docs/getting-started/shared.tsx
> +      additionalPackages ? additionalPackages?.join(' ') : ''
```suggestion
      additionalPackages ? additionalPackages.join(' ') : ''
```

2023-10-06 10:20 UTC, igalklebanov commented
We need to somehow mention that it also uses Tarn for connection pool management and provide a link to tarn's documentation.
https://github.com/kysely-org/kysely/pull/724/files#diff-f8ce7b5d9b471415c6e85f9db24baf58b16c5a55101d354bf66c0dc497340671R105-R109

2023-10-06 10:24 UTC, igalklebanov commented
Regarding Deno compatibility, here's an official [issue](https://github.com/denoland/deno/issues/18303) that seems related to the problem (and someone claimed it still doesn't work 2 weeks ago despite being closed).

2023-10-06 10:27 UTC, igalklebanov commented
Regarding Bun compatibility, here's an [issue](https://github.com/oven-sh/bun/issues/5147) that seems related to the problem (all commenters use libraries that use tedious under the hood).

2023-10-07 00:35 UTC, gittgott commented
Hey @igalklebanov
I should have everything covered that you brought up.

Thanks for all your work maintaining this library by the way. You all do an amazing job.
I'm quite ecstatic that mssql is becoming part of the core dialects.

2023-10-07 19:00 UTC, igalklebanov reviewed
Looks good!

Just a small correction..

2023-10-09 07:36 UTC, igalklebanov requested changes
![image](https://github.com/kysely-org/kysely/assets/14938291/55adba34-6640-4a4f-a583-8229e8ccbf1d)
something's missing in "getting started -> querying".

2023-10-09 18:21 UTC, gittgott commented
Hey @igalklebanov,

Sorry about that. I ran into some issues getting that one to work and forgot about it (and didn't run typecheck 🤦‍♂️)

I meant to ask: what would be a preferable solution for inserting a new row and returning data from that inserted row while #687 is still open?
The only thought I had was to use that existing findPeople function and grab the first of the array that's returned. Here's the snippet for that:
```typescript
export async function createPerson(person: NewPerson) {
  await db.insertInto('person')
    .values(person)
    .executeTakeFirstOrThrow()

  const newPerson = (await findPeople(person)).at(-1)
  return newPerson
}

export async function deletePerson(id: number) {
  const person = await findPersonById(id)

  if (person) {
    await db.deleteFrom('person').where('id', '=', id).execute()
  }

  return person
}
```

I think that the data will be sorted by id, so this would grab the most recently inserted row, but there would be issues if something was inserted to the table with identical values between the insertInto line and newPerson line were executed.

Am I missing something or would there be no better option until the output clause is supported?

2023-11-07 10:59 UTC, igalklebanov commented
@gittgott I'd prefer using [scope identity](https://learn.microsoft.com/en-us/sql/t-sql/functions/scope-identity-transact-sql?view=sql-server-ver16&redirectedfrom=MSDN) in a transaction.

2023-12-31 00:26 UTC, igalklebanov approved these changes

2023-12-31 00:26 UTC, merged